from pgdrift.commands import (
    snapshot_cmd,
    diff_cmd,
    report_cmd,
    watch_cmd,
    history_cmd,
    baseline_cmd,
    tag_cmd,
    lint_cmd,
    ignore_cmd,
    mask_cmd,
    redact_cmd,
    schedule_cmd,
    threshold_cmd,
    plugin_cmd,
    scorecard_cmd,
    filter_cmd,
    variance_cmd,
    maturity_cmd,
    stale_cmd,
    drift_age_cmd,
    pin_cmd,
    compare_cmd,
    policy_cmd,
    similarity_cmd,
    revert_cmd,
    impact_cmd,
    health_cmd,
    complexity_cmd,
)

_MODULES = [
    snapshot_cmd,
    diff_cmd,
    report_cmd,
    watch_cmd,
    history_cmd,
    baseline_cmd,
    tag_cmd,
    lint_cmd,
    ignore_cmd,
    mask_cmd,
    redact_cmd,
    schedule_cmd,
    threshold_cmd,
    plugin_cmd,
    scorecard_cmd,
    filter_cmd,
    variance_cmd,
    maturity_cmd,
    stale_cmd,
    drift_age_cmd,
    pin_cmd,
    compare_cmd,
    policy_cmd,
    similarity_cmd,
    revert_cmd,
    impact_cmd,
    health_cmd,
    complexity_cmd,
]


def register_all(sub):
    for mod in _MODULES:
        mod.register(sub)
